import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "./components/providers/ConvexClientProvider";
import Navbar from "./components/Navbar";
import { Toaster } from "sonner";
import Stripe from "stripe";
import { StripeTestNotice } from "./components/StripeTestNotice";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Stripe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen relative antialiased`}>
        <Toaster position="top-right" />
        <div className="absolute top-0 -z-10 inset-0 min-h-screen w-full bg-white">
          <div className="absolute bottom-auto left-auto right-20 top-0 h-[500px] w-[500px] -translate-x-[30%] translate-y-[20%] rounded-full bg-[rgba(173,109,244,0.5)] opacity-50 blur-[80px]"></div>
        </div>
        <ConvexClientProvider>
          <Navbar />
          {children}
        </ConvexClientProvider>
        <StripeTestNotice />
      </body>
    </html>
  );
}
